elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  image: nrithyamelk_elasticsearch
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  image: nrithyamelk_logstash
  links:
    - elasticsearch:elasticsearch
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  image: kibana:4.1.1
  links:
    - elasticsearch:elasticsearch
