elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    #basic config hence I have not set any env
  
    LOGSPOUT: ignore 
  command: -f /etc/logstash.sample.conf
kibana:
  ports:
    - "80:5601"
